config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root :to => "posts#index"
  resources :posts do
    resources :comments, :except => [:show, :index]
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  validates :body, :presence => true

end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :comments
  validates :title, :presence => true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_filter :authenticate_user!, except: [:index, :show]
  
  def new
    @post = Post.find(params[:post_id])
    @comment = Comment.new
  end

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.new(comment_params)
    if @comment.save
      flash[:notice] = "Comment Successfully added!"
      redirect_to post_path(@comment.post)
    else
      render :new
    end
  end

  def edit
    # binding.pry
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
  end

  def update
    @comment = Comment.find(params[:id])
    @post = Post.find(params[:post_id])
    if @comment.update(comment_params)
      flash[:notice] = "Comment successfully Updated!"
      redirect_to post_path(@post)
    else
      render :edit
    end
  end

  private
  def comment_params
    params.require(:comment).permit(:body)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :authenticate_user!, except: [:index, :show]
  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    date = Date.today

    @post[:date] = date
    if @post.save
      flash[:notice] = @post.title + " successfully added!"
      redirect_to posts_path
    else
      render :new
    end
  end

  def destroy
    @post = Post.find(params[:id])

    if @post.destroy
      flash[:notice] = @post.title + " successfully deleted!"
      redirect_to posts_path
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      flash[:notice]="Post successfully Updated!"
      redirect_to posts_path
    else
      render :edit
    end
  end

  private
    def post_params
      params.require(:post).permit(:title, :date, :body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/_form.html.erb
<%= render 'layouts/errors', :object => @comment %>

<%= form_for [@post, @comment] do |f| %>
<%= f.label :body %>
<%= f.text_area :body, cols:40, rows: 4 %>
<br>
<br>
<%= f.submit %>
<% end %>

app/views/comments/_form_comment.html.erb
<%= render 'layouts/errors', :object => @comment %>

<%= form_for [@post, @comment] do |f| %>
<%= f.label :body %>
<%= f.text_area :body, cols:40, rows: 4 %>
<br>
<br>
<%= f.submit %>
<% end %>

app/views/comments/edit.html.erb
<h1>Edit Comment</h1>
<%= render 'form' %>

app/views/comments/new.html.erb
<h1>Add a comment</h1>
<%= render 'form' %>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
<h3> Errors were made: Try again.</h3>
<ul>
  <% object.errors.full_messages.each do |m| %>
  <li> <%= m %> </li>
  <% end %>
</ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BlogApp | <%= yield(:title) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= flash[:alert] %>
<%= flash[:notice] %>

<% if user_signed_in? %>
  Logged in as <%= current_user.email %>
  <%= link_to 'Edit Profile', edit_user_registration_path %> |
  <%= link_to 'Logout', destroy_user_session_path, method: :delete %>
  <% else %>
    <%= link_to "Sign Up", new_user_registration_path %> |
    <%= link_to "Login", new_user_session_path %>
    <% end %>

<%= yield %>

</body>
</html>

app/views/posts/_form.html.erb
<%= render 'layouts/errors', :object => @post %>

<%= form_for @post do |f| %>
<%= f.label :title %>
<%= f.text_field :title %>
<br>
<% f.label :body %>
<%= f.text_area :body, cols: 100, rows: 40 %>
<br>
<%= f.submit %>
<% end %>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>

<%= render 'form' %>

app/views/posts/index.html.erb
<h1>Blog Posts</h1>
<ul>
  <% @posts.each do |p| %>
    <li><%= link_to p.title, post_path(p) %> </li>
  <% end %>
</ul>

<p><%= link_to "Add Post", new_post_path %></p>

app/views/posts/new.html.erb
<h1>New Post</h1>

<% if @post.errors.any? %>
  <h3> Errors were made: Try again.</h3>
  <ul>
    <% @post.errors.full_messages.each do |m| %>
      <li> <%= m %> </li>
    <% end %>
  </ul>
<% end %>
<%= form_for @post do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <br>
  <% f.label :body %>
  <%= f.text_area :body, cols: 100, rows: 40 %>
  <br>
  <%= f.submit %>
<% end %>

app/views/posts/show.html.erb
<% content_for(:title, @post.title) %>
<h1><%= @post.title %></h1>
<% if @post.date != nil %>
  <h4><%= @post.date.to_s %></h4>
<% end %>
<p><%= link_to "Edit", edit_post_path(@post) %> </p>
<p><%= link_to "Delete", post_path(@post), :data => {:confirm => "For real?", :method => "delete"} %></p>
<p><%= link_to "Add a Comment", new_post_comment_path(@post) %>

<h4><%= @post.body %></h4>

<% if @post.comments.any? %>
  <h4>Comments:</h4>
  <ul>
    <% @post.comments.each do |c| %>
    <li>
      <%= c.body %> |
      <%= link_to "Edit", edit_post_comment_path(@post, c) %> |
      <%= link_to "Delete", post_comment_path(@post, c), :data => {:confirm => "Are you sure?", :method => "delete"} %>
    </li>
    <% end %>
  </ul>
  <% else %>
    <p>
      There are no comments yet!
    </p>
  <% end %>
<p> <%= link_to "Return to Blog Posts", posts_path %> </p>